### ISSUE TITLE
Reenable support for Embedded Opacity slider in layer tree

### ISSUE THREAD

**Issue by YoannQDQ** [YoannQDQ/qgis-layer-tree-icons#1]
Enabling EmbeddedWidgets  (`QgsLayerTreeModel.UseEmbeddedWidgets`) on a custom layer tree model causes crash when moving the layer tree nodes around. Therefore, it was disabled in Layer Tree Icons.

**Comment by francis33** [comment]
Hello,

I have exactlly the same issue. Enabling the plugin disable the Opacity slider in layer tree.
This is an excellent plugin ... and the Opacity slider in layer tree is really usefull.

Combining both would be great !  :-)

Best
Francis

**Comment by YoannQDQ** [comment]
Fixed in 1.3.0
