### ISSUE TITLE
Incompatible with other custom context menus

### ISSUE THREAD

**Issue by freeshrugsxd** [YoannQDQ/qgis-layer-tree-icons#3]
Hey,

I've written [a small QGIS plugin](https://github.com/freeshrugsxd/qgis-pathfinder) and I want to thank you because your plugin has been of great help to me and a huge source of inspiration!
That being said, I noticed a compatibility issue when using my plugin together with yours. Since we both create custom context menus via an event listener, only one of them is actually displayed in QGIS. I don't have a solution for this right now but I would like to ensure that future versions will work with other custom context menus.

I just wanted to bring this to your attention as you may also be interested in finding a solution for this.

**Comment by YoannQDQ** [comment]
Thanks for bringing this to my attention. I refactored the context menu in the version 1.5.0 of my plugin, with a working but kinda hackish solution. I wrote an explanation in the README file:

https://github.com/YoannQDQ/qgis-layer-tree-icons#hackish-resolution

**Comment by freeshrugsxd** [comment]
Hey @YoannQDQ, just pinging to tell you that I am about to upgrade pathfinder to a version where I modify the context menu via the layerTreeView().contextMenuAboutToShow signal instead of an event filter. This removes the need for the layer tree context menu manager class -- but again creates an incompatibility with plugins that add context menu entries via other means, like an event filter. Multiple plugins hooking in contextMenuAboutToShow have all their entries displayed, however. I think this is the best way going forward.

Thanks again for implementing this years ago, it served me well

Greetings
