### ISSUE TITLE
Python error after installing version 1.4.0

### ISSUE THREAD

**Issue by Alexander-Orlovsky** [YoannQDQ/qgis-layer-tree-icons#6]
After installing the plugin version 1.4.0, a Python error occurred.
This problem did not occur until version 1.3.1 inclusive.
Installing the new version 1.5.0 did not solve the problem.

![2020-10-23_23-18-38](https://user-images.githubusercontent.com/40177482/97052060-ff6cfb80-1588-11eb-86bb-9caf9a5b573d.png)

**Comment by YoannQDQ** [comment]
Sorry to hear that. I'll look into it.

**Comment by YoannQDQ** [comment]
FIxed in 1.5.1

**Comment by Alexander-Orlovsky** [comment]
Now everything is great!
Thank you very much!!!
A magical and very useful plugin.
My students especially like it  :)

**Comment by YoannQDQ** [comment]
You're welcome. Glad they like it :)
