### ISSUE TITLE
Crash withe new QGIS Version 3.18 Zurich

### ISSUE THREAD

**Issue by francis33** [YoannQDQ/qgis-layer-tree-icons#7]
Hi,

Seems that the plugin make the new version of QGIS (3.18 Zurich) crash.

A the first stage of the lauching of QGIS, an error message appears (attached file)
And just after, the new version of QGIS systematicaly crash.

Is it an plugin issue ? Or my computer config ?
It worked perfectly with the 3.16 (Hannover) QGIS version.

Best
Francis

![2021-02-27_14-38-03](https://user-images.githubusercontent.com/53442186/109391379-1648a380-7917-11eb-8d9c-edf741578bad.jpg)

**Comment by marcomile** [comment]
Hi ... same thing happens to me too only with version 3.18
